"""Fold current block

This plug-in can be used to quickly fold the active block.
"""

###############################################################################
# No user customization below this line
###############################################################################

import GPS
from gps_utils import interactive


def __contextualMenuFilter(context):
    
    # Check if the context is generated by the source editor
    if not (context.module_name == 'Source_Editor'):
        return False
    
    # Get current view
    ev = GPS.EditorBuffer.get().current_view()
            
    # Return true if the cursor is at a valid block
    if ev.cursor().block_type() != 'CAT_UNKNOWN':
        return True
    else:
        return False


def __contextualMenuLabel(context):
    
    # Name of the menu item
    return 'Fold current block'


@interactive(
    name       ='Fold current block',
    contextual = __contextualMenuLabel,
    filter     = __contextualMenuFilter)
def on_activate():
    
    # Get current view
    ev = GPS.EditorBuffer.get().current_view()
    
    # Fold block
    ev.cursor().block_start().block_fold()
